engine/proxy.go
engine/proxy_test.go
urlutil/urlutil.go

In order to proxy a local service, Lava needs to know the port used by
the service. This PR makes possible to guess the port, if it is not
specified, based on the scheme of the target URL. For instance, 443
for `https://`, 9418 for `git://`, etc.

engine: try to guess target port when generating proxy streams

---

internal/config/catalog.go
internal/config/catalog_test.go

Emit an error when there is no catalogue configured in lava.yaml

internal/config: error when no catalog urls are present

---

go.mod
go.sum
internal/engine/targetserver.go

This PR fixes a bug on how `*targetServer.handle` handles errors
coming from `*proxy.Group.ListenAndServe`.
This PR also updates github.com/jroimartin/proxy to v0.3.1.
github.com/jroimartin/proxy@v0.3.1 fixes `*Group.ListenAndServe` error
handling. For more details, please see https://github.com/jroimartin/proxy/pull/12

internal/engine: fix bug handling proxy.Group errors

---

go.mod
go.sum
internal/engine/targetserver.go

This PR upgrades github.com/jroimartin/proxy to v0.4.2, which improves
event and error handling.
For more details, see the following PRs:
- https://github.com/jroimartin/proxy/pull/13
- https://github.com/jroimartin/proxy/pull/15

go.mod, internal/engine: upgrade github.com/jroimartin/proxy to v0.4.2

---

go.mod
go.sum

This PR upgrades github.com/jroimartin/proxy to v0.4.3.
For more details, please see:
- https://github.com/jroimartin/proxy/pull/16

go.mod: upgrade github.com/jroimartin/proxy to v0.4.3

---

cmd/lava/internal/run/run.go
internal/config/config.go
internal/config/config_test.go
internal/report/jsonprinter.go
internal/report/jsonprinter_test.go
internal/report/report.go
internal/report/report_test.go

This PR adds a new report writer.
As preliminary steps to that, it parses the report generated by vulcan-agent and filters the vulnerabilities according to their severity and exclusion criteria.

report: implement report writer

---

cmd/lava/internal/run/run.go
internal/config/config.go

Fix `config.Exclusion` docs to match the behavior introduced in the
following PR:
- https://github.com/adevinta/lava/pull/10

internal/config: fix config.Exclusion docs

---

internal/report/report.go
internal/report/report_test.go

This PR allows to use the configuration field
`report.exclusions.resource` to exclude vulnerabilities whose resource
or resource string fields match the provided regular expression.

internal/report: exclude vulnerabilities by resource string

---

internal/report/report.go

Before, `jsonPrinter` would print `null` if there are no
vulnerabilities. After this change, it prints `[]`.

internal/report: print empty array in JSON output if no vulns

---

cmd/lava/internal/run/run.go

This PR adds the `-forcecolor` flag to the run command.
The `-forcecolor` flag forces colorized output. By default, colorized
output is disabled in the following cases:
- Lava is not executed from a terminal.
- Lava is executed from a `dumb` terminal.
- The `NO_COLOR` environment variable is set (regardless of its value).
This new flag allows to force colorized output in GitHub Actions.

cmd/lava: add -forcecolor flag to run command

---

cmd/lava/internal/run/run.go
internal/config/config.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go
internal/report/report.go

This PR adds the functionality to gather metrics along the Lava scanning process.
To enable the functionality, you only have to add a key `metrics`, and as value the output file, in the report section of the configuration file and a file will appear when the execution of the scan finishes.
List of collected metrics:
- Lava Version: `lava_version`
- Total amount of excluded vulnerabilities: `excluded`. These vulnerabilities are not included in the count of vulnerabilities per severity.
- Vulnerabilities per severity: `vulnerabilities`
- Targets: `targets`
- Exit Code: `exit_code`
- Execution Time: `execution_time`
- Duration: `duration`

all: collect metrics

---

cmd/lava/internal/help/help.go
cmd/lava/internal/help/helpdoc.go
cmd/lava/main.go

This PR implements built-in docs in the Lava command. This enables the
Lava command to be self-documented. It also adds a placeholder for the
documentation of the Lava configuration file format.

cmd/lava: implement built-in docs

---

cmd/lava/internal/scan/scan.go
cmd/lava/internal/scan/scan_test.go

This PR modifies the Lava command so it does not change the current
working directory before executing a scan. This makes easier to use
configuration files that are stored in locations different to the one
of the target project.

cmd/lava: do not change the current working directory on 'lava scan'

---

internal/urlutil/urlutil.go

This PR fixes the error returned by `urlutil.getHTTP` when the
specified URL returns a status code different to `200 OK`.
It changes the error from:
```
error: engine run: get checkype catalog: get "https://example.com/checktypes.json": %!w(<nil>)
```
To:
```
error: engine run: get checkype catalog: get "https://example.com/checktypes.json": invalid status code: 404
```

internal/urlutil: fix invalid status code error

---

internal/checktype/checktype.go
internal/checktype/checktype_test.go
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/critical_severity.yaml
internal/config/testdata/debug_log_level.yaml
internal/config/testdata/invalid_lava_version.yaml
internal/config/testdata/invalid_log_level.yaml
internal/config/testdata/invalid_output_format.yaml
internal/config/testdata/invalid_pull_policy.yaml
internal/config/testdata/invalid_severity.yaml
internal/config/testdata/invalid_target_asset_type.yaml
internal/config/testdata/json_output_format.yaml
internal/config/testdata/never_pull_policy.yaml
internal/config/testdata/no_checktypes_urls.yaml
internal/config/testdata/no_target_identifier.yaml
internal/config/testdata/no_targets.yaml
internal/config/testdata/valid.yaml

Calling `checktype.NewCatalog` with no URLs should be valid. In that
case, the returned catalog will be empty.
At the same time, we want to force users to provide at least one
catalog URL in the configuration file. Otherwise, no security checks
would be run, which is not an obvious behavior. Thus, this commit
moves this validation to the config package, which also validates that
at least one target is provided.

internal: move validation of number of checktypes URLs to config package

---

cmd/lava/internal/help/helpdoc.go
internal/config/config.go

Although Lava depends on Docker right now, there is no reason to not
support other container runtimes in the future. Thus, we should avoid
references to any specific runtime in all public interfaces and docs.

all: remove references to Docker from docs

---

cmd/lava/internal/scan/scan.go
internal/engine/engine.go
internal/report/report.go

This PR revisits the current metrics collection implemented in Lava. It makes the following changes:
**Rename fields**
- Rename `execution_time` to `start_time`. I think `execution_time` can be confusing as it could refer to when the scan started or what was its duration.
- Rename `lava_version` to `config_version`. There is in fact two different versions: the minimum version required by the config (`config_version`) and the version of the Lava command used to run the scan (`lava_version`). The latter is not used yet, so it will be added in future PRs.
- Rename `excluded` to `excluded_vulnerability_count`. It is true that `excluded_vulnerability_count` is longer but it is also more explicit. `excluded` could be confused with the exclusions present in the config.
- Rename `vulnerabilities` …

internal, cmd/lava: revisit metrics collection

---

cmd/lava/internal/scan/scan.go
cmd/lava/internal/scan/scan_test.go
cmd/lava/internal/version/version.go
cmd/lava/main.go
internal/config/config.go
internal/config/config_test.go

This PR changes the Lava command to check that the provided
configuration is compatible with the version of the command.
The version of the command is read at runtime using
`debug.ReadBuildInfo`. This approach works with `go install` and
[goreleaser][goreleaser-get-version].
[goreleaser-get-version]: https://goreleaser.com/cookbooks/build-go-modules/#getting-the-version-from-the-module

cmd/lava: check config compatibility

---

cmd/lava/internal/scan/scan.go
internal/report/human.tmpl
internal/report/humanprinter.go
internal/report/humanprinter_test.go
internal/report/jsonprinter.go
internal/report/jsonprinter_test.go
internal/report/report.go
internal/report/report_test.go

This PR print the status of every check as part of the human-readable
report. It also makes Lava to exit with code greater than 0 if any
check has failed.
I also took the opportunity to rename `sum` variables to `summ`, which
I feel is a more obvious abbreviation of summary.

internal/report: print check status, return exit code greater than 0 on check error

---

.golangci.yaml

Allow any year in the headers.
With this change we avoid errors when we update files created in previous years.

.golangci.yaml: allow any year in the headers

---

cmd/lava/internal/initialize/default.yaml

This PR removes the Adevinta copyright disclaimer from the yaml file
generated by `lava init`. This command is run by end-users to generate
an initial lava.yaml, so this file should not include such disclaimer.

cmd/lava: remove Adevinta copyright from 'lava init' output

---

cmd/lava/internal/initialize/default.yaml

This PR changes the asset type of the default target created by
`lava init` from `GitRepository` to `Path`. `GitRepository` only
allows paths corresponding to Git repositories, whereas `Path` allows
any path. Thus, `Path` seems more sensible for the default target.

cmd/lava: use 'Path' as default target in 'lava init' output

---

internal/config/config.go
internal/config/testdata/invalid_lava_version.yaml
internal/config/testdata/no_checktypes_urls.yaml

This PR ensures that the keys in the configuration file exist as
fields in the struct being decoded into.

internal/config: validate config file schema

---

cmd/lava/internal/help/helpdoc.go
cmd/lava/internal/scan/scan.go
cmd/lava/main.go

Colorized output depends on the environment where lava is
executed. Thus, an environment variable seems a better fit for this
configuration. Otherwise, every lava command that outputs colors would
require a `-forcecolor` flag.

cmd/lava: force colorized output via environment variable

---

cmd/lava/internal/base/base.go
cmd/lava/internal/help/help.go
cmd/lava/internal/help/helpdoc.go
cmd/lava/internal/scan/scan.go
cmd/lava/main.go

This pull request fixes inconsistencies and style issues in the
builtin help. For instance, the description of the lava command is now
closer to the one in the README file. It also adds a reference to the
environment variable `LAVA_RUNTIME` in `lava help scan`. So, it is
easier to discover it.

cmd/lava: fix inconsistencies and style issues in builtin help

---

cmd/lava/internal/help/help.go
cmd/lava/main.go

Change the output for help topics from stderr to stdout.

cmd/lava: change the output to stdout for help topics

---

cmd/lava/internal/help/helpdoc.go

The `lava.yaml` examples in documentation specify `lava: v1.0.0`,
which is higher than the latest Lava version (v0.4.1). This makes Lava
to exit with error in the case of using the examples as a starting
point. The examples use v1.0.0 because that will be the first Lava
stable release. However, it is true that right now it is misleading.
This PR updates the documentation to specify v0.0.0. This will be
changed again before releasing Lava v1.0.0.

cmd/lava: use v0.0.0 for the lava.yaml examples in the documentation

---

cmd/lava/internal/help/helpdoc.go
cmd/lava/internal/scan/scan.go

This PR adds a field with the version of the Lava command to the
metrics file. This allows to track adoption and fragmentation.

cmd/lava: record Lava command version in metrics file

---

.github/workflows/golangci-lint.yaml

This commit updates golangci-lint to v1.57.2.

.github/workflows: update golangci-lint to v1.57.2

---

internal/engine/targetserver.go

Lava currently reports a warning message when a target cannot be
handled by the engine's target server:
2024-04-28T11:55:40+02:00 WARN could not handle target
target={alpine:latest DockerImage map[]} err=generate stream:
get target addr: invalid asset type: DockerImage
In some cases, for instance when the target is a DockerImage, this is
expected. However, it can be misleading for users that do not know the
Lava internal details. Thus, this commit makes the target server
explicitly handle supported asset types.

internal/engine: make target server ignore unsupported asset types

---

cmd/lava/internal/help/helpdoc.go
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/invalid_env.yaml
internal/config/testdata/valid_env.yaml

This pr allows to reference env variables in the config file.
The format must be `\$\{[a-zA-Z_][a-zA-Z_0-9]*\}`  (i.e.  `${MY_ENV1}`).

internal/config: add support for env variables

---

cmd/lava/internal/help/help.go

This PR makes the help topics more pleasant to read to read both in
the CLI and the online docs.
Before:
After:

cmd/lava: show usage line as code block in "lava help"

---

cmd/lava/internal/run/run.go
cmd/lava/internal/run/run_test.go
cmd/lava/internal/run/testdata/lava-run-test/.dockerignore
internal/containers/containers.go
internal/containers/containers_test.go
internal/engine/engine_test.go

This PR fixes a bug when "lava run" builds a Docker image with the
same ID as the previous one. This bug can happen when the checktype
has not changed between runs. In this scenario, the run command would
delete the new image just after building it and before running the
check. If the pull policy is `IfNotPresent`, Docker tries to find an
image with the same name in the configured registry. Otherwise, if the
pull policy is `Never`, Docker fails straight away because the image
is not in the local Docker cache anymore.

cmd/lava/internal/run: do not remove Docker image if the ID has not changed

---

cmd/lava/internal/run/run.go

This PR adds the name of the variables passed with the `-var` flag to
the list of required variables of the checktype created by `lava run`
so they are passed to the check.

cmd/lava/internal/run: add -var names to checktype's required vars

---

cmd/lava/internal/run/run.go

This PR adds a reference to `LAVA_RUNTIME` in `lava help run`.

cmd/lava/internal/run: add reference to LAVA_RUNTIME in help

---

cmd/lava/internal/help/helpdoc.go
cmd/lava/main.go

Create a new topic, checktypes, in the Lava help command.

cmd/lava: add checktypes to help topics

---

cmd/lava/internal/help/helpdoc.go
cmd/lava/internal/run/run.go
cmd/lava/internal/run/runflag.go
cmd/lava/internal/run/runflag_test.go
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/low_show.yaml
internal/report/report.go
internal/report/report_test.go

This PR adds the field `report.show` to the Lava configuration
file. It allows to specify the minimum severity required to show a
finding. Similarly, it adds the flag `-show` to the `lava run`
command.
This change allows to use different severity thresholds to exit with
error and to generate the report.

cmd/lava: allow to specify the minimum severity required to show a finding

---

cmd/lava/internal/help/helpdoc.go
internal/report/human.tmpl

This PR implements two changes in Lava's human-readable output:
- Show vulnerability fingerprint, so it is easier to exclude
vulnerabilities by this criteria.
- Split resource rows with hyphens, so it is easier to read the
resource tables.
Before,
```
=== [GO-2021-0113] Out-of-bounds read in golang.org/x/text/language (HIGH) ===
TARGET
/home/n/tmp/govulncheck-test/
AFFECTED RESOURCE
Module golang.org/x/text@v0.3.5 at sub1/go.mod:1
DESCRIPTION
Out-of-bounds read in golang.org/x/text/language
DETAILS
Your code calls vulnerable functions in 1 package (golang.org/x/text/language).
RECOMMENDATIONS
- Visit the linked references for more details.
REFERENCES
- https://pkg.go.dev/vuln/GO-2021-0113
RESOURCES
- A summarized code flow for vulnerable function golang.org/x/text/language.Parse:
module: …
```

internal/report/human: add fingerprint, split resource rows

---

cmd/lava/internal/help/helpdoc.go
cmd/lava/internal/scan/scan.go
internal/config/config.go
internal/report/human.tmpl
internal/report/humanprinter.go
internal/report/humanprinter_test.go
internal/report/jsonprinter.go
internal/report/jsonprinter_test.go
internal/report/report.go
internal/report/report_test.go

Lava outputs a warning if an exclusion rule does not match any finding. 
A new parameter, `error_on_stale_exclusions,` has been added to the configuration if we want to exit with an exit code when there are unused exclusions.
The goal is to avoid staled exclusion rules.

internal/report: detect unused exclusions

---

cmd/lava/internal/run/run.go
cmd/lava/internal/scan/scan.go
internal/config/config.go
internal/config/config_test.go
internal/engine/engine.go
internal/engine/engine_test.go
internal/report/report.go
internal/report/report_test.go

As part of the future development of the functionality that will allow importing configurations, we need to be able to distinguish those settings that have not been specified in the configuration but which until now have been automatically assigned a default value.
Therefore, these settings are now converted into pointers.

internal/config: allow nils for settings with default values

---

go.mod
go.sum
internal/config/merge.go
internal/config/merge_test.go

This PR contains the functionality to merge configurations.

internal/config: add merging configuration functionality
